config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :articles do
    resources :comments
  end

  root :to => 'articles#index'
  get '/articles/hashtag/:name', to: 'articles#hashtag'
  get '/articles/user/:user_id', to: 'articles#user'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	has_and_belongs_to_many :tags
	belongs_to :user

	validates :title, presence: true
	validates :body, presence: true

	is_impressionable

	after_create do
		hashtags = self.body.scan(/#\w+/)
		hashtags.map!(&:downcase)		
		hashtags.uniq.map do |hashtag|
			tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
			self.tags << tag
		end
	end

	after_update do
		self.tags.clear
		hashtags = self.body.scan(/#\w+/)
		hashtags.map!(&:downcase)
		hashtags.uniq.map do |hashtag|
			tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
			self.tags << tag
		end
	end

	def self.search(search)
		if search
			where(["lower(title) LIKE ?" , "%#{search.downcase}%"])
		else
			all
		end
	end


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :articles
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :articles
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :hashtag, :user]
  before_action :article_owner, only: [:edit, :update, :destroy]

  impressionist
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.search(params[:search]).order("created_at DESC")
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
  end

  def hashtag
    tag = Tag.find_by(name: params[:name])
    @articles = tag.articles.order("created_at DESC")
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
  end

  def user
    user = User.find(params[:user_id])
    @articles = user.articles.order("created_at DESC")
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
  end

  def article_owner
    unless (current_user.email ==  @article.user.email) || (current_user.email == "levantien83@gmail.com")
      flash[:notice] = 'Access denied as you are not owner of this Article'
      redirect_to articles_url
    end
  end

  # GET /articles/new
  def new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(params[:comment].permit(:name, :body))
		
		redirect_to @article		
	end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		
		redirect_to @article		
	end
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def render_with_hashtags(text)
		text.gsub(/#\w+/){|word| link_to word, "/articles/hashtag/#{word.downcase.delete('#')}"}.html_safe
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/application/_footer.html.erb
<div class="bg-inverse" align="center">
	<div class="container"><br>
		<P>Creative Bloq is part of Valentine, an international media group and leading digital publisher. Visit our corporate site.
		</P>
		
		<div class="dropdown-divider"></div>
		<nav class="nav nav-inline">
			<a class="nav-link" href="#">About us</a>   |
			<a class="nav-link" href="#">Terms and conditions</a>   |
			<a class="nav-link" href="#">Privacy policy</a>   |
			<a class="nav-link" href="#">Cookies policy</a>   |
			<a class="nav-link" href="#">Advertise with us</a>
			
		</nav>
		<div class="dropdown-divider"></div>
		<P>© Valentine Publishing Limited Quay House, The Ambury, Bath BA1 1UA. All rights reserved. England and Wales company registration number 1008888.</P>

	</div>
</div>

app/views/application/_header.html.erb
<header class="navbar navbar-dark navbar-static-top bd-navbar bg-inverse" role="banner"> 
	<div class="clearfix">
		<button class="navbar-toggler pull-xs-right hidden-sm-up collapsed" type="button" data-toggle="collapse" data-target="#bd-main-nav" aria-expanded="false">
			☰
		</button>
		<a class="navbar-brand hidden-sm-up" href="/">
			Valentine's blog
		</a>
	</div>
	<div class="navbar-toggleable-xs collapse" id="bd-main-nav" aria-expanded="false" style="height: 0px;">
		<nav class="nav navbar-nav">
			<a class="navbar-brand" href="/" onclick="ga('send', 'event', 'Navbar', 'Community links', '/');">Valentine's blog</a>
			<a class="nav-item nav-link active" href="/" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Home');">Home</a>
			<a class="nav-item nav-link " href="#" onclick="ga('send', 'event', 'Navbar', 'Community links', 'About');">About</a>

			<div class="nav navbar-nav" align="right">
				<form class="form-inline">
					<% if user_signed_in? %>						
						<div class="form-group btn-group">
						  <button class="btn btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						    <%= current_user.email %>
						  </button>
						  <div class="dropdown-menu">
						  	<%= link_to("User's articles", 
										"/articles/user/#{current_user.id}",	
										class: 'dropdown-item'
										) %>

						    <div class="dropdown-divider"></div>

						    <%= link_to('Change password', 
										edit_user_registration_path,	
										class: 'dropdown-item'
										) %>
							<%= link_to('Sign out', 
										destroy_user_session_path, 
										:method => :delete,
										class: 'dropdown-item'
										) %>
						  </div>
						</div>
												
					<% else %>						
						<div class="form-group btn-group">
						  <button class="btn btn-info btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						    Not signed in
						  </button>
						  <div class="dropdown-menu">
							<%= link_to('Sign up', 
											new_user_registration_path,	
											class: 'dropdown-item'
											) %>
							<%= link_to('Sign in', 
											user_session_path,				
											class: 'dropdown-item'
											) %>
						  </div>
						</div>						
					<% end -%>

					<div class="form-group">				  	
					  	<%= form_tag articles_path, :method => 'get' do %>
						<%= text_field_tag :search, params[:search], class: 'form-control form-control-sm' %>
						<%= submit_tag "Search", class: 'btn btn-info-outline btn-sm' %>
						<% end %>
					</div>							

				</form>

			</div>

		</nav>
	</div>
</header>

app/views/application/_sidebar.html.erb
<br>
	<div align="right">
		<h3>Website</h3>
		<%= link_to( 'Home', "/", class: 'dropdown-item' ) %>
		<%= link_to( 'About', "#", class: 'dropdown-item' ) %>	
		
		<div class="dropdown-divider"></div>
		<h3>Social</h3>
		<%= link_to( 'Twitter', "#", class: 'dropdown-item' ) %>
		<%= link_to( 'Facebook', "#", class: 'dropdown-item' ) %>
		<%= link_to( 'Github', "#", class: 'dropdown-item' ) %>
		<%= link_to( 'Email', "#", class: 'dropdown-item' ) %>

		<div class="dropdown-divider"></div>
		<h3>Hashtag</h3>
		<% @all_tags = Tag.all %>
		<% @all_tags.each do |t| %>
			<% if t.articles.count == 0 %>
			<% else %>
				<%= link_to "#{t.name} (#{t.articles.count})", "/articles/hashtag/#{t.name}" %>
			<% end -%>
		<% end -%>
		
		<div class="dropdown-divider"></div>
		<h3>Last articles</h3>
		<% @last_articles = Article.order("created_at DESC").limit(5) %>
		<% @last_articles.each do |a| %>
			<%= link_to a.title, article_path(a) %>
			<br>
		<% end -%>
	</div>

app/views/application/_tag.html.erb
<%= Tag.each do |t| %>
<% link_to t, "/articles/hashtag/#{t.name}" %>

app/views/articles/_article.html.erb
<div class="row">  
  <div class="card">
    <div class="card-block">
      <h4 class="card-title"><%= article.title %></h4>
      <p class="blockquote-footer">
        Submitted <%= time_ago_in_words(article.created_at) %> ago by <%= link_to article.user.email,"/articles/user/#{article.user.id}" %> | 
        <%= article.impressionist_count %> views 
      </p>
      <p class="text-justify"><%= @markdown.render(render_with_hashtags(article.body)).html_safe %></p>          
    </div>
    <div class="card-footer">
      <div class="row">
        <div class="col-md-6">
          <%= link_to "#{article.comments.count} comments", article %>
        </div>
        <% if user_signed_in? && (current_user == article.user || current_user.email == "levantien83@gmail.com") %>
          <div class="col-md-6" align="right">
            <%= link_to 'Edit', edit_article_path(article) %> |
            <%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        <% end -%>
      </div>
    </div>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="container"><br><br>
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: 'form-control' %>
    </div><br>
    <div class="field">
      <%= f.label :body %><br>
      <%= f.text_area :body, class: 'form-control', rows: '3' %>
    </div><br>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div><br>
<% end %>

app/views/articles/edit.html.erb
<div class="container">
	<h1>Editing Article</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @article %> |
	<%= link_to 'Back', articles_path %>
</div>

app/views/articles/hashtag.html.erb
<div class="container">	
	<%= render @articles %>  
</div>

app/views/articles/index.html.erb
<div class="container">	
	<%= render @articles %>  
</div>

app/views/articles/new.html.erb
<div class="container">
	<h1>New Article</h1>

	<%= render 'form' %>

	<%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<div class="container">
  <%= render @article %>
  <br>
  <% if @article.comments.count > 0 %>
    <div class="card card-block">    
      <%= render @article.comments %>
    </div>
    <br>
  <% end %>
    
  <div class="col-md-6 col-md-offset-3">
    <h5>
      Add a comment:
    </h5>
    <%= render "comments/form" %>        
  </div>
</div>

app/views/articles/user.html.erb
<div class="container">	
	<%= render @articles %>  
</div>

app/views/comments/_comment.html.erb
<blockquote class="blockquote"> 

  <h5>
    <%= comment.name %>
  </h5>  

  <small>
    <%= @markdown.render(comment.body).html_safe %>      
  </small>

  <footer class="blockquote-footer">
    Submitted <%= time_ago_in_words(comment.created_at) %> ago | 
    <%= link_to 'Delete', [comment.article, comment],
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
  </footer>

</blockquote>
    

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
	
	<div>	    
		<%= f.label :name %><br>
		<%= f.text_field :name, class: 'form-control' %>
    	<br>	    
		<%= f.label :body %><br>
		<%= f.text_area :body, class: 'form-control', rows: '3' %>
    	<br>	    
      	<%= f.submit %>
	    
  	</div><br>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Valentine's Blog</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		
		<%= render "header" %>
		<div class="row">
			<div class="col-md-3">				
			</div>
			<div class="col-md-8">
				<p class="notice"><%= notice %></p>
				<p class="alert"><%= alert %></p>
				<% if user_signed_in? %>
					<%= link_to 'New Article', new_article_path, class: 'btn btn-primary-outline btn-sm' %>	
				<% end -%>				
			</div>			
		</div><br>	
		<div class="row">
			<div class="col-md-3">
				<div class="container">
					<%= render "sidebar" %>
				</div>
			</div>
			<div class="col-md-8">
				<%= yield %>
			</div>			
		</div>		

		<%= render "footer" %>
		
	</body>
</html>

app/views/users/articles.html.erb
<div class="container">
	

	<%= link_to 'New Article', new_article_path %>
	<br>
	<%= render articles/@articles %>
  
  
</div>